import requests
import csv
import time
import os
from dotenv import load_dotenv

load_dotenv()

USER_AGENT = os.getenv("USER_AGENT")

def get_lat_lon_nominatim(location_name):
    base_url = f'https://nominatim.openstreetmap.org/search?q={location_name}&format=json&limit=1'

    headers = {
        "accept-language": "en",
        "user-agent": USER_AGENT
    }

    try:
        response = requests.get(base_url, headers=headers)
        
        # Check if the request was successful
        if response.status_code == 200:
            data = response.json()

            # If the API returns results
            if data:
                lat = data[0]['lat']
                lon = data[0]['lon']
                return lat, lon
            else:
                print(f"{location_name}: No results found")
                return None, None
        else:
            print(f"Error: Received status code {response.status_code} for {location_name}")
            return None, None

    except requests.exceptions.RequestException as e:
        # Handle network-related errors (e.g., timeouts)
        print(f"Request failed for {location_name}. Error: {e}")
        return None, None

# List of UK town names
towns = ['Abengourou', 
'Amsterdam', 
'Ardkeen', 
'Ardmillan', 
'Athens', 
'Auchenreoch', 
'Balgrochan', 
'Ballycarry', 
'Ballydrain', 
'Ballygowan', 
'Ballymacarret', 
'Ballywalter', 
'Balmoral', 
'Balmore', 
'Bangor', 
'Banstead', 
'Bar Hall', 
'Barcelona', 
'Bardowie', 
'Barnehurst', 
'Barnes Cray', 
'Barnsbury', 
'Bayswater', 
'Bearsden', 
'Beccles', 
'Bedworth', 
'Belfast', 
'Belgravia', 
'Bellahill', 
'Belvedere', 
'Berlin', 
'Bexley', 
'Bexleyheath', 
'Birdston', 
'Birmingham', 
'Bishopbriggs', 
'Blackfen', 
'Blairskaith', 
'Bognor Regis', 
'Bridgend', 
'Brixton', 
'Broadford', 
'Brompton', 
'Buchley', 
'Buckie', 
'Budapest', 
'Burgess Hill', 
'Burghead', 
'Cadder', 
'Canonbury', 
'Carrickfergus', 
'Carrowdore', 
'Chertsey', 
'Chichester', 
'Clachan Of Campsie', 
'Clapham', 
'Clapham Park', 
'Clerkenwell', 
'Cliftonville', 
'Cloghy', 
'Coedpoeth', 
'Coldblow', 
'Colston', 
'Comber', 
'Conlig', 
'Copthorne', 
'Cork', 
'Crawfordsburn', 
'Crawley', 
'Crayford', 
'Cullen', 
'Cultra', 
'Cunningburn', 
'Donaghadee', 
'Drumhirk', 
'Dublin', 
'Dufftown', 
'East Grinstead', 
'East Wickham', 
'Eden', 
'Edinburgh', 
'Egham', 
'Elgin', 
'Erith', 
'Exeter', 
'Falconwood', 
'Farnham', 
'Finaghy', 
'Findhorn', 
'Findochty', 
'Finsbury', 
'Finsbury Park', 
'Fluchter', 
'Fochabers', 
'Foots Cray', 
'Forres', 
'Furzedown', 
'Glastry', 
'Godalming', 
'Greencastle', 
'Greenisland', 
'Greyabbey', 
'Groomsport', 
'Guildford', 
'Hamberg', 
'Harestanes', 
'Haverhill', 
'Hayston', 
'Haywards Heath', 
'Helens Bay', 
'Hereford', 
'High Gallowhill', 
'Highbury', 
'Holywood', 
'Hopeman', 
'Horsham', 
'Ipswich', 
'Islington', 
'Kearney', 
'Keith', 
'Kenilworth', 
'Kennington', 
'Killinchy', 
'Kilroot', 
'Kinloss', 
'Kircubbin', 
'Kirkintilloch', 
'Kirkistown', 
'Knight\'s Hill', 
'Knock', 
'Knockandhu', 
'Knockando', 
'Knockbog', 
'Lambeth', 
'Leatherhead', 
'Leeds', 
'Legoniel', 
'Lennoxtown', 
'Lenzie', 
'Lessness Heath', 
'Lhanbryde', 
'Lintmill', 
'Lisbon', 
'Lisson Grove', 
'Little Green', 
'Littlehampton', 
'Llan-Y-Pwll', 
'Llanarmon Dyffryn ...', 
'Llay', 
'Llwydarth', 
'Llwynmawr', 
'Lochhill', 
'London', 
'Longlands', 
'Lossiemouth', 
'Lower Auchenreath', 
'Lower Holloway', 
'Lowestoft', 
'Madrid', 
'Maesteg', 
'Maggieknockater', 
'Maida Vale', 
'Manchester', 
'Marchwiel', 
'Marford', 
'Marylebone', 
'Marypark', 
'Mawdlam', 
'Mayfair', 
'Merehead', 
'Merthyr Mawr', 
'Milan', 
'Mill Hills', 
'Mill Street', 
'Millersneuk', 
'Millisle', 
'Milltown Of Auchinhove', 
'Milltown Of Edinvillie', 
'Milngavie', 
'Milton', 
'Milton Of Campsie', 
'Miltonduff', 
'Minera', 
'Moats Tye', 
'Monks Eleigh', 
'Monks Kirby', 
'Monwode Lea', 
'Moreton Morrell', 
'Moreton Paddox', 
'Morton Bagot', 
'Moss', 
'Moss Of Barmuckity', 
'Moss-Side', 
'Mosstodloch', 
'Moulton', 
'Mount Pleasant', 
'Mount Sion', 
'Mountain Ash', 
'Mousley End', 
'Moycroft', 
'Muir Of Lochs', 
'Mulben', 
'Munich', 
'Mutford', 
'Mynachdy', 
'Myton', 
'Nacton', 
'Nant-Y-Moel', 
'Nantgarw', 
'Nantyffyllon', 
'Napton On The Hill', 
'Naughton', 
'Nayland', 
'Neal\'s Green', 
'Nebsworth', 
'Nether Dallachy', 
'Nether Whitacre', 
'Nethercote', 
'Nethermills', 
'New Arley', 
'New Bilton', 
'New Brighton', 
'New Broughton', 
'New Elgin', 
'New End', 
'New York', 
'Newbold On Avon', 
'Newbold Pacey', 
'Newbold-On-Stour', 
'Newbridge', 
'Newcastle', 
'Newhall Green', 
'Newnham', 
'Newton', 
'Newton Regis', 
'Newtown', 
'Newtownards', 
'Nextend', 
'No Man\'s Heath', 
'Norbridge', 
'North Cornelly', 
'North Cray', 
'North End', 
'North Green', 
'Northend', 
'Northumberland Heath', 
'Norton', 
'Norton Canon', 
'Norton Lindsey', 
'Norton Little Green', 
'Norwich', 
'Nottage', 
'Nowton', 
'Nuneaton', 
'Nuns Quarter', 
'Nutfield', 
'Oak Hill', 
'Oakley', 
'Oakley Park', 
'Occold', 
'Ocle Pychard', 
'Offton', 
'Ogmore Vale', 
'Old Arley', 
'Old Bexley', 
'Old Country', 
'Old Felixstowe', 
'Old Forge', 
'Old Gore', 
'Old Newton', 
'Old Wharf', 
'Oldhall Green', 
'Onehouse', 
'Orcop', 
'Orcop Hill', 
'Orford', 
'Orleton Common', 
'Ormeau', 
'Oslo', 
'Otley', 
'Oulton', 
'Oulton Broad', 
'Ousden', 
'Outwood', 
'Overton', 
'Overton Bridge', 
'Oxgang', 
'Oxshott', 
'Oxted', 
'Pachesham Park', 
'Paddington', 
'Page\'s Green', 
'Pains Hill', 
'Painters Green', 
'Pakefield', 
'Pakenham', 
'Palermo', 
'Palgrave', 
'Palmers Cross', 
'Pandy', 
'Pant', 
'Pant-Y-Pyllau', 
'Pant-Yr-Awel', 
'Paradise Green', 
'Parham', 
'Paris', 
'Park Barn', 
'Park Gate', 
'Park Lane', 
'Parkgate', 
'Parkside', 
'Parkway', 
'Parliament Heath', 
'Parton', 
'Paynes Green', 
'Peartree Green', 
'Peaslake', 
'Peasmarsh', 
'Pembridge', 
'Pen-Rhos', 
'Pen-Y-Bryn', 
'Pen-Y-Cae', 
'Pen-Y-Fai', 
'Pen-Y-Park', 
'Pen-Y-Rhiw', 
'Pen-Yr-Englyn', 
'Pen-Yr-Heol', 
'Pencoed', 
'Pencombe', 
'Pencraig', 
'Penderyn', 
'Pendre', 
'Penguithal', 
'Penley', 
'Penprysg', 
'Penrhiwceiber', 
'Penrhiwfer', 
'Penrhos', 
'Penrhys', 
'Pentonville', 
'Pentre', 
'Pentre Broughton', 
'Pentre Bychan', 
'Pentre Cilgwyn', 
'Pentre Maelor', 
'Pentrebach', 
'Penycae', 
'Penygraig', 
'Penywaun', 
'Peper Harow', 
'Perrystone Hill', 
'Perthcelyn', 
'Perton', 
'Peterchurch', 
'Peterstow', 
'Phocle Green', 
'Pikestye', 
'Pillerton Hersey', 
'Pillerton Priors', 
'Pimlico', 
'Pipe And Lyde', 
'Pipe Aston', 
'Pirbright', 
'Pirbright Camp', 
'Pitch Place', 
'Pixham', 
'Pixley', 
'Plaistow', 
'Plas Coch', 
'Plough Hill', 
'Polesden Lacey', 
'Polesworth', 
'Poling', 
'Poling Corner', 
'Ponciau', 
'Pont Rhyd-Y-Cyff', 
'Pont Siôn Norton', 
'Pont-Y-Blew', 
'Pont-Y-Rhyl', 
'Pontfadog', 
'Pontrilas', 
'Pontshill', 
'Pontyclun', 
'Pontycymer', 
'Pontygwaith', 
'Pontypridd', 
'Pool Head', 
'Poolmill', 
'Portaferry', 
'Portavogie', 
'Portfield', 
'Portgordon', 
'Porth', 
'Porthcawl', 
'Portknockie', 
'Portslade-By-Sea', 
'Portway', 
'Pot Common', 
'Pound Hill', 
'Povey Cross', 
'Poynings', 
'Prague', 
'Preston Bagot', 
'Preston Fields', 
'Prey Heath', 
'Price Town', 
'Prinsted', 
'Pulborough', 
'Pyecombe', 
'Pyrford Village', 
'Quags Corner', 
'Queens Island', 
'Regent\'s Park', 
'Reigate', 
'Rhigos', 
'Rhiwceiliog', 
'Rhiwinder', 
'Rhondda', 
'Rhydyfelin', 
'Ringboy', 
'Robertstown', 
'Rome', 
'Rosebank', 
'Rothes', 
'Royal Leamington Spa', 
'Rugby', 
'Russ Hill', 
'Rydens', 
'Rydeshill', 
'Salfords', 
'Sarn', 
'Shankill', 
'Shelf', 
'Sidcup', 
'Six Road Ends', 
'Skegoniel', 
'Slade Green', 
'Soho', 
'South Cornelly', 
'South Lambeth', 
'Springfield', 
'St James', 
'St John\'s Wood', 
'St Luke\'s', 
'Staines', 
'Stanleytown', 
'Stanwell', 
'Stockholm', 
'Stockwell', 
'Stormont', 
'Strand', 
'Stranmillis', 
'Stratford-Upon-Avon', 
'Streatham', 
'Streatham Hill', 
'Streatham Park', 
'Streatham Vale', 
'Sunbury', 
'Sydenham', 
'Taffs Well', 
'Talbot Green', 
'Thamesmead', 
'Thomastown', 
'Ton Pentre', 
'Ton-Teg', 
'Torrance', 
'Tremains', 
'Tulse Hill', 
'Twechar', 
'Ty\'n-Y-Garn', 
'Tylagwyn', 
'Tylorstown', 
'Tynant', 
'Tynewydd', 
'Tyntetown', 
'Tythegston', 
'Upper Boat', 
'Upper Church Village', 
'Vauxhall', 
'Walton-On-Thames', 
'Warsaw', 
'Warwick', 
'Waterside', 
'Wattstown', 
'Waun Y Gilfach', 
'Welling', 
'Wern Tarw', 
'West Dulwich', 
'West Heath', 
'West Norwood', 
'Westbourne Green', 
'Westminster', 
'Whitehead', 
'Whitehouse Lower', 
'Whitehouse Upper', 
'Whiterock', 
'Wig Fach', 
'Wild Mill', 
'Williamstown', 
'Windsor', 
'Woodburn', 
'Wrexham', 
'Wyndham', 
'Ynysybwl',]

# Storing the results to a local CSV under town_lat_lons.csv within the processed folder

with open('../../data/processed/seed_data/town_lat_lons.csv', mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['Town', 'Latitude', 'Longitude'])

    # Looping through the towns and get latitudes and longitudes

    for town in towns:
        lat, lon = get_lat_lon_nominatim(town)
        if lat and lon:
            print(f"{town}: Latitude = {lat}, Longitude = {lon}")
            writer.writerow([town, lat, lon])
        else:
            print(f"{town}: No results found")
        
        time.sleep(2)

print("Latitudes and Longitudes have been saved to 'town_lat_lons.csv'.")